// web/app/m/compare/page.tsx
"use client";

import {
  useCallback,
  useEffect,
  useState,
  type FormEvent,
} from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  Banknote,
  Building2,
  Check,
  Clock,
  Landmark,
  Lightbulb,
  type LucideIcon,
  MessageSquare,
  Scale,
  Search,
  ShieldCheck,
  TrendingUp,
  X,
} from "lucide-react";
import {
  compareCompanies,
  getCompanyAnalysis,
  getCompanySummary,
  searchCompanies,
} from "@/lib/api";
import {
  CompanyAnalysisResponse,
  CompanyListItem,
  CompanySummaryResponse,
  CompareResponse,
  DIMENSIONS_META,
  DIMENSION_ACCENT,
  DIMENSION_LABELS,
  DIMENSION_ORDER,
  LEVEL_COLORS,
} from "@/lib/types";

const DIMENSION_ICON_MAP: Record<string, LucideIcon> = {
  landmark: Landmark,
  banknote: Banknote,
  "shield-check": ShieldCheck,
  clock: Clock,
  "trending-up": TrendingUp,
  "message-square": MessageSquare,
};

const COMPARE_KEY = "zjob_compare_ids";
const MAX_COMPARE = 2;

export default function MobileComparePage() {
  const router = useRouter();
  const [mode, setMode] = useState<"select" | "compare">("select");
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [keyword, setKeyword] = useState("");
  const [results, setResults] = useState<CompanyListItem[]>([]);
  const [summaryMap, setSummaryMap] = useState<
    Record<number, CompanySummaryResponse>
  >({});
  const [loading, setLoading] = useState(false);

  // 对比模式数据
  const [data, setData] = useState<CompareResponse | null>(null);
  const [analysisMap, setAnalysisMap] = useState<
    Record<number, CompanyAnalysisResponse>
  >({});
  const [compareLoading, setCompareLoading] = useState(false);

  // 初始化：读取已选公司 ID
  useEffect(() => {
    const stored = localStorage.getItem(COMPARE_KEY);
    const ids: number[] = stored ? JSON.parse(stored) : [];
    setSelectedIds(ids);
  }, []);

  // 加载公司列表
  const loadCompanies = useCallback(async (kw: string) => {
    setLoading(true);
    try {
      const list = await searchCompanies(kw, 50, 0);
      setResults(list);
      const summaries = await Promise.all(
        list.map((c) => getCompanySummary(c.id))
      );
      const next: Record<number, CompanySummaryResponse> = {};
      for (const s of summaries) {
        if (s) next[s.company_id] = s;
      }
      setSummaryMap(next);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadCompanies("");
  }, [loadCompanies]);

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    loadCompanies(keyword.trim());
  };

  const handleClear = () => {
    setKeyword("");
    loadCompanies("");
  };

  const persist = (ids: number[]) => {
    localStorage.setItem(COMPARE_KEY, JSON.stringify(ids));
  };

  const toggleSelect = (id: number) => {
    setSelectedIds((prev) => {
      let next: number[];
      if (prev.includes(id)) {
        next = prev.filter((x) => x !== id);
      } else if (prev.length >= MAX_COMPARE) {
        // 已满 2 个，替换最早的一个
        next = [...prev.slice(1), id];
      } else {
        next = [...prev, id];
      }
      persist(next);
      return next;
    });
  };

  const removeSelected = (id: number) => {
    setSelectedIds((prev) => {
      const next = prev.filter((x) => x !== id);
      persist(next);
      return next;
    });
  };

  const startCompare = async () => {
    if (selectedIds.length !== 2) return;
    setMode("compare");
    setCompareLoading(true);
    try {
      const res = await compareCompanies(selectedIds);
      if (res) {
        setData(res);
        const analyses = await Promise.all(
          res.companies.map((c) => getCompanyAnalysis(c.company_id))
        );
        const next: Record<number, CompanyAnalysisResponse> = {};
        for (let i = 0; i < res.companies.length; i++) {
          if (analyses[i]) {
            next[res.companies[i].company_id] = analyses[i]!;
          }
        }
        setAnalysisMap(next);
      }
    } finally {
      setCompareLoading(false);
    }
  };

  const backToSelect = () => {
    setMode("select");
    setData(null);
    setAnalysisMap({});
  };

  // 已选公司详情（用于顶部 chips 显示名称）
  const selectedCompanies = selectedIds
    .map((id) => results.find((c) => c.id === id))
    .filter((c): c is CompanyListItem => !!c);

  // ============ 对比模式 ============
  if (mode === "compare") {
    return (
      <div>
        <div className="sticky top-0 z-20 bg-background/95 backdrop-blur border-b border-border">
          <div className="max-w-[430px] mx-auto px-4 h-14 flex items-center justify-between">
            <button
              onClick={backToSelect}
              className="inline-flex items-center gap-2 text-sm font-medium text-foreground"
            >
              <ArrowLeft className="w-5 h-5" />
              <span>返回选择</span>
            </button>
            <span className="text-sm font-semibold text-foreground">
              1v1 对比
            </span>
          </div>
        </div>

        {compareLoading ? (
          <div className="max-w-[430px] mx-auto px-4 py-6 space-y-4">
            <div className="h-10 rounded-lg bg-secondary animate-pulse" />
            <div className="h-32 rounded-xl bg-secondary animate-pulse" />
            <div className="h-64 rounded-xl bg-secondary animate-pulse" />
          </div>
        ) : data && data.companies.length === 2 ? (
          <CompareDetail
            data={data}
            analysisMap={analysisMap}
            onRemove={(id) => {
              removeSelected(id);
              backToSelect();
            }}
          />
        ) : (
          <div className="max-w-[430px] mx-auto px-4 py-20 text-center text-sm text-muted-foreground">
            对比数据加载失败，请重试
          </div>
        )}
      </div>
    );
  }

  // ============ 选择模式 ============
  return (
    <div className="pb-[calc(64px+64px+env(safe-area-inset-bottom,0px))]">
      {/* 顶栏 */}
      <div className="sticky top-0 z-20 bg-background/95 backdrop-blur border-b border-border">
        <div className="max-w-[430px] mx-auto px-4 h-14 flex items-center justify-between">
          <button
            onClick={() => router.push("/m")}
            className="inline-flex items-center gap-2 text-sm font-medium text-foreground"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>返回</span>
          </button>
          <h1 className="text-base font-semibold text-foreground">公司对比</h1>
          <span className="w-12" />
        </div>
      </div>

      <div className="max-w-[430px] mx-auto px-4">
        {/* 说明 */}
        <div className="pt-4 pb-3">
          <div className="flex items-center gap-2 mb-1">
            <Scale className="w-5 h-5 text-muted-foreground" />
            <h2 className="text-lg font-semibold text-foreground">
              1v1 对比
            </h2>
          </div>
          <p className="text-xs text-muted-foreground">
            从下方选择 2 家公司，查看六维横向对比与真实时薪
          </p>
        </div>

        {/* 搜索框 */}
        <form onSubmit={onSubmit} className="pb-3">
          <div className="flex items-center bg-card border border-border rounded-full px-3 h-10 shadow-card">
            <Search className="w-4 h-4 text-muted-foreground shrink-0" />
            <input
              type="text"
              value={keyword}
              onChange={(e) => setKeyword(e.target.value)}
              placeholder="搜索公司名称"
              className="flex-1 min-w-0 bg-transparent border-0 outline-none text-sm text-foreground placeholder:text-muted-foreground px-2"
            />
            {keyword && (
              <button
                type="button"
                onClick={handleClear}
                className="text-muted-foreground hover:text-foreground"
                aria-label="清空"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>
        </form>

        {/* 已选公司 chips */}
        {selectedCompanies.length > 0 && (
          <div className="flex flex-wrap items-center gap-2 pb-3">
            {selectedCompanies.map((c) => (
              <span
                key={c.id}
                className="inline-flex items-center gap-1.5 h-8 pl-3 pr-1.5 rounded-full bg-primary text-primary-foreground text-xs font-medium"
              >
                {c.short_name || c.name}
                <button
                  type="button"
                  onClick={() => removeSelected(c.id)}
                  className="w-5 h-5 rounded-full inline-flex items-center justify-center hover:bg-primary-foreground/20"
                  aria-label={`移除${c.name}`}
                >
                  <X className="w-3 h-3" />
                </button>
              </span>
            ))}
            {selectedIds.length < MAX_COMPARE && (
              <span className="text-xs text-muted-foreground">
                再选 {MAX_COMPARE - selectedIds.length} 家
              </span>
            )}
          </div>
        )}

        {/* 公司列表 */}
        {loading ? (
          <div className="space-y-2 py-2">
            {[0, 1, 2, 3, 4].map((i) => (
              <div
                key={i}
                className="h-16 rounded-lg bg-secondary animate-pulse"
              />
            ))}
          </div>
        ) : results.length === 0 ? (
          <div className="py-16 text-center text-muted-foreground">
            <p className="mb-2">未找到相关公司</p>
            <p className="text-xs">试试其他关键词</p>
          </div>
        ) : (
          <div className="space-y-2">
            {results.map((c) => (
              <CompanySelectCard
                key={c.id}
                company={c}
                summary={summaryMap[c.id]}
                selected={selectedIds.includes(c.id)}
                onToggle={() => toggleSelect(c.id)}
              />
            ))}
          </div>
        )}
      </div>

      {/* 底部操作栏（位于底部导航栏之上） */}
      <div
        className="fixed left-0 right-0 z-40 border-t border-border bg-background/95 backdrop-blur"
        style={{ bottom: "calc(64px + env(safe-area-inset-bottom, 0px))" }}
      >
        <div className="max-w-[430px] mx-auto px-4 py-3 flex items-center gap-3">
          <div className="flex-1 text-xs text-muted-foreground">
            已选 <span className="font-semibold text-foreground">{selectedIds.length}</span> / {MAX_COMPARE}
          </div>
          <button
            type="button"
            onClick={startCompare}
            disabled={selectedIds.length !== 2}
            className="inline-flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-5 h-10 text-sm font-semibold shadow-card disabled:opacity-50 disabled:shadow-none transition-opacity"
          >
            <Scale className="w-4 h-4" />
            开始 1v1 对比
          </button>
        </div>
      </div>
    </div>
  );
}

// ============ 选择卡片 ============
function CompanySelectCard({
  company,
  summary,
  selected,
  onToggle,
}: {
  company: CompanyListItem;
  summary?: CompanySummaryResponse;
  selected: boolean;
  onToggle: () => void;
}) {
  const score = summary?.overall_score;
  return (
    <div
      className={`flex items-center gap-3 bg-card border rounded-lg p-3 shadow-card transition-colors ${
        selected
          ? "border-primary ring-1 ring-primary/30"
          : "border-border"
      }`}
    >
      <Link
        href={`/m/company/${company.id}`}
        className="flex items-center gap-3 flex-1 min-w-0"
      >
        <div className="w-9 h-9 rounded-md bg-secondary flex items-center justify-center text-muted-foreground shrink-0">
          <Building2 className="w-4 h-4" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-0.5">
            <h3 className="text-sm font-semibold text-foreground truncate">
              {company.name}
            </h3>
            {score != null && (
              <span
                className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-semibold shrink-0"
                style={{
                  backgroundColor: "var(--emote-mint-100)",
                  color: "var(--emote-mint-900)",
                }}
              >
                {(score / 10).toFixed(1)}
              </span>
            )}
          </div>
          <p className="text-xs text-muted-foreground truncate mb-1.5">
            {company.industry || "未知行业"} · {company.scale || "未知规模"}
          </p>
          {summary && (
            <div className="flex items-center gap-1">
              {summary.dimensions.map((dim) => {
                const color = LEVEL_COLORS[dim.level];
                const meta = DIMENSIONS_META.find((m) => m.key === dim.key);
                const Icon = meta
                  ? DIMENSION_ICON_MAP[meta.icon] ?? Landmark
                  : Landmark;
                return (
                  <span
                    key={dim.key}
                    className="inline-flex items-center justify-center w-5 h-5 rounded"
                    style={{
                      backgroundColor: `${color.hex}22`,
                      color: color.hex,
                    }}
                    title={`${dim.label} ${dim.score}分`}
                  >
                    <Icon className="w-3 h-3" />
                  </span>
                );
              })}
            </div>
          )}
        </div>
      </Link>
      <button
        type="button"
        onClick={onToggle}
        aria-label={selected ? "移出对比" : "加入对比"}
        className={`shrink-0 w-10 h-10 rounded-full flex items-center justify-center transition-all active:scale-90 ${
          selected
            ? "bg-primary text-primary-foreground"
            : "text-muted-foreground hover:text-primary hover:bg-secondary"
        }`}
      >
        {selected ? (
          <Check className="w-5 h-5" />
        ) : (
          <Scale className="w-5 h-5" />
        )}
      </button>
    </div>
  );
}

// ============ 对比详情 ============
function CompareDetail({
  data,
  analysisMap,
  onRemove,
}: {
  data: CompareResponse;
  analysisMap: Record<number, CompanyAnalysisResponse>;
  onRemove: (id: number) => void;
}) {
  const companies = data.companies;

  return (
    <div className="max-w-[430px] mx-auto px-4 py-6 space-y-6">
      {/* 已选公司头卡（左右布局 + VS） */}
      <section className="relative">
        <div className="grid grid-cols-2 gap-2 items-stretch">
          {companies.map((c) => {
            const score = c.overall_score;
            const scoreColor =
              score >= 80
                ? { bg: "var(--emote-mint-100)", text: "var(--emote-mint-700)" }
                : score >= 60
                ? { bg: "var(--emote-cream-100)", text: "var(--emote-cream-700)" }
                : { bg: "var(--emote-rose-100)", text: "var(--emote-rose-700)" };
            return (
              <article
                key={c.company_id}
                className="relative rounded-lg border border-border bg-card p-2 shadow-card flex flex-col min-w-0"
              >
                <button
                  onClick={() => onRemove(c.company_id)}
                  className="absolute -top-1.5 -right-1.5 w-5 h-5 rounded-full bg-card border border-border inline-flex items-center justify-center text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors shadow z-10"
                  aria-label={`删除${c.name}`}
                >
                  <X className="w-3 h-3" />
                </button>
                <div className="min-w-0 flex-1 pr-1">
                  <h2 className="text-xs font-bold text-foreground leading-snug line-clamp-2">
                    {c.short_name || c.name}
                  </h2>
                </div>
                <div className="mt-1.5 flex items-baseline gap-1.5 flex-wrap">
                  <span className="text-xl font-extrabold text-foreground leading-none">
                    {(score / 10).toFixed(1)}
                  </span>
                  <span
                    className="text-[9px] font-medium px-1.5 py-px rounded-full"
                    style={{
                      backgroundColor: scoreColor.bg,
                      color: scoreColor.text,
                    }}
                  >
                    综合
                  </span>
                </div>
              </article>
            );
          })}
        </div>
        {/* VS 徽章（居中覆盖） */}
        <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-20 pointer-events-none">
          <span className="inline-flex items-center justify-center w-8 h-8 rounded-full bg-primary text-primary-foreground text-[10px] font-extrabold shadow-lg border-2 border-background">
            VS
          </span>
        </div>
      </section>

      {/* 结论摘要 */}
      <section className="rounded-xl border border-border bg-secondary/40 p-4">
        <div className="flex items-start gap-3">
          <Lightbulb
            className="w-5 h-5 mt-0.5 shrink-0"
            style={{ color: "var(--emote-cream-500)" }}
          />
          <div>
            <h3 className="text-sm font-semibold text-foreground">结论摘要</h3>
            <p className="mt-1 text-sm leading-relaxed text-foreground/90">
              {companies
                .map((c) => c.name)
                .join("、")}
              已完成 1v1 对比，综合评分最高的是
              {companies.reduce((max, c) =>
                c.overall_score > max.overall_score ? c : max
              ).name}
              。
            </p>
          </div>
        </div>
      </section>

      {/* 六维逐项对比（卡片行样式，避免维度名换行） */}
      <section className="rounded-xl border border-border bg-card p-3 shadow-card space-y-2">
        <h3 className="text-sm font-semibold text-foreground px-1 mb-1">
          六维度逐项对比
        </h3>
        {DIMENSION_ORDER.map((dimKey) => {
          const label = DIMENSION_LABELS[dimKey];
          const meta = DIMENSIONS_META.find((m) => m.key === dimKey);
          const accent = meta ? DIMENSION_ACCENT[meta.accent] : DIMENSION_ACCENT.charcoal;
          const Icon = meta
            ? DIMENSION_ICON_MAP[meta.icon] ?? Landmark
            : Landmark;
          // 确定本维度 2 家公司中最高分（用于胜出高亮）
          const scores = companies.map((c) => {
            const dim = c.dimensions.find((d) => d.key === dimKey);
            return dim ? dim.score : 0;
          });
          const maxScore = Math.max(...scores);
          return (
            <div
              key={dimKey}
              className="flex items-center gap-3 px-2 py-2 rounded-lg bg-secondary/30"
            >
              {/* 维度信息（左列：图标 + 名称，固定宽度避免换行） */}
              <div className="flex items-center gap-2 shrink-0 w-[110px] min-w-0">
                <span
                  className={`w-7 h-7 rounded-md flex items-center justify-center shrink-0 ${accent.bg} ${accent.text}`}
                  title={meta?.oneLiner}
                >
                  <Icon className="w-4 h-4" />
                </span>
                <span
                  className="text-xs font-semibold text-foreground truncate"
                  title={label}
                >
                  {label}
                </span>
              </div>
              {/* 分隔竖线 */}
              <div className="w-px h-6 bg-border shrink-0" />
              {/* 每家公司的分数（等宽两列，中间分隔） */}
              {companies.map((c, idx) => {
                const dim = c.dimensions.find((d) => d.key === dimKey);
                const score = dim ? dim.score : 0;
                const isWin = score > 0 && score === maxScore;
                const color = dim
                  ? LEVEL_COLORS[dim.level].hex
                  : "var(--emote-charcoal-300)";
                return (
                  <div key={c.company_id} className="flex-1 min-w-0 flex items-center gap-2">
                    <div className="flex-1 min-w-0">
                      <div
                        className={`text-[10px] text-muted-foreground truncate mb-0.5 ${
                          isWin ? "text-foreground" : ""
                        }`}
                        title={c.short_name || c.name}
                      >
                        {c.short_name || c.name}
                      </div>
                      <div className="flex items-center gap-1.5">
                        <div className="flex-1 h-1.5 rounded-full bg-secondary overflow-hidden">
                          <div
                            className="h-full rounded-full"
                            style={{
                              backgroundColor: color,
                              width: `${(score / 100) * 100}%`,
                            }}
                          />
                        </div>
                        <span
                          className={`text-xs font-extrabold leading-none ${
                            isWin ? "text-foreground" : "text-foreground/80"
                          }`}
                        >
                          {(score / 10).toFixed(1)}
                        </span>
                      </div>
                    </div>
                    {/* 胜者小皇冠指示 */}
                    {isWin && scores[0] !== scores[1] && (
                      <span className="shrink-0 w-4 h-4 rounded-full bg-emote-cream-100 text-emote-cream-700 inline-flex items-center justify-center" title="本项领先">
                        <TrendingUp className="w-2.5 h-2.5" />
                      </span>
                    )}
                  </div>
                );
              })}
            </div>
          );
        })}
      </section>

      {/* 真实时薪对比 */}
      {(() => {
        const hourlyWages: Record<number, number> = {};
        companies.forEach((c) => {
          const hw =
            analysisMap[c.company_id]?.real_hourly_wage?.hourly_wage;
          if (typeof hw === "number" && !Number.isNaN(hw) && hw > 0)
            hourlyWages[c.company_id] = hw;
        });
        const hasAny = Object.keys(hourlyWages).length > 0;
        if (!hasAny) return null;
        const maxWage = Math.max(...Object.values(hourlyWages));
        return (
          <section className="rounded-xl border border-border bg-card p-3 shadow-card space-y-3">
            <div className="flex items-center gap-2">
              <Banknote className="w-4 h-4 text-muted-foreground" />
              <h3 className="text-sm font-semibold text-foreground">
                真实时薪对比
              </h3>
            </div>
            <div className="grid grid-cols-2 gap-3">
              {companies.map((c) => {
                const analysis = analysisMap[c.company_id];
                const hw = analysis?.real_hourly_wage;
                const wage = hourlyWages[c.company_id] ?? 0;
                const p50 = hw?.industry_p50_hourly ?? 0;
                const monthly = hw?.monthly_take_home;
                const hours = hw?.monthly_work_hours;
                const percent = hw?.percentile;
                const heightPct = maxWage > 0 ? (wage / maxWage) * 100 : 0;
                const color =
                  p50 > 0 && wage >= p50
                    ? "var(--emote-mint-500)"
                    : "var(--emote-cream-500)";
                return (
                  <div
                    key={c.company_id}
                    className="rounded-lg bg-secondary/30 p-2.5 flex flex-col gap-1.5"
                  >
                    <div className="text-[11px] font-semibold text-foreground truncate">
                      {c.short_name || c.name}
                    </div>
                    {wage > 0 ? (
                      <>
                        <div className="flex items-baseline gap-1.5">
                          <span className="text-2xl font-extrabold text-foreground leading-none">
                            ¥{wage.toFixed(0)}
                          </span>
                          <span className="text-[10px] text-muted-foreground">
                            /小时
                          </span>
                        </div>
                        <div className="h-2 w-full rounded-full bg-secondary overflow-hidden mt-1">
                          <div
                            className="h-full rounded-full transition-all"
                            style={{
                              width: `${heightPct}%`,
                              backgroundColor: color,
                            }}
                          />
                        </div>
                        <div className="mt-1 grid grid-cols-2 gap-x-2 gap-y-0.5 text-[10px] text-muted-foreground">
                          {typeof monthly === "number" && (
                            <div>
                              月到手{" "}
                              <span className="text-foreground font-semibold">
                                ¥{(monthly / 1000).toFixed(1)}k
                              </span>
                            </div>
                          )}
                          {typeof hours === "number" && (
                            <div>
                              月工时{" "}
                              <span className="text-foreground font-semibold">
                                {hours.toFixed(0)}h
                              </span>
                            </div>
                          )}
                          {p50 > 0 && (
                            <div>
                              行业P50{" "}
                              <span className="text-foreground font-semibold">
                                ¥{p50.toFixed(0)}
                              </span>
                            </div>
                          )}
                          {typeof percent === "number" && (
                            <div>
                              行业分位{" "}
                              <span className="text-foreground font-semibold">
                                P{percent}
                              </span>
                            </div>
                          )}
                        </div>
                        {hw?.verdict && (
                          <p className="mt-1 text-[10px] leading-snug text-muted-foreground line-clamp-3">
                            {hw.verdict}
                          </p>
                        )}
                      </>
                    ) : (
                      <div className="py-3 text-center text-[11px] text-muted-foreground">
                        暂无时薪数据
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
            <p className="text-[10px] text-muted-foreground leading-snug">
              * 真实时薪 = 月到手收入 ÷ 月工时（含加班），仅供参考
            </p>
          </section>
        );
      })()}

      {/* 综合维度进度条对比 */}
      <section className="rounded-xl border border-border bg-card p-4 shadow-card">
        <div className="flex items-center gap-2 mb-4">
          <Scale className="w-5 h-5 text-muted-foreground" />
          <h3 className="text-sm font-semibold text-foreground">
            综合维度对比
          </h3>
        </div>
        <div className="space-y-3">
          {DIMENSION_ORDER.map((dimKey) => {
            const label = DIMENSION_LABELS[dimKey];
            const scores = companies.map((c) => {
              const dim = c.dimensions.find((d) => d.key === dimKey);
              return dim ? dim.score : 0;
            });
            const maxScore = Math.max(...scores, 1);
            return (
              <div key={dimKey}>
                <div className="flex items-center justify-between text-xs mb-1">
                  <span className="font-medium text-foreground">{label}</span>
                </div>
                <div className="space-y-1.5">
                  {companies.map((c) => {
                    const dim = c.dimensions.find((d) => d.key === dimKey);
                    const score = dim ? dim.score : 0;
                    const widthPct = (score / maxScore) * 100;
                    const color = dim
                      ? LEVEL_COLORS[dim.level].hex
                      : "var(--emote-charcoal-300)";
                    return (
                      <div
                        key={c.company_id}
                        className="flex items-center gap-2"
                      >
                        <span className="text-xs text-muted-foreground w-12 truncate">
                          {c.short_name}
                        </span>
                        <div className="flex-1 h-2 rounded-full bg-secondary overflow-hidden">
                          <div
                            className="h-full rounded-full"
                            style={{
                              backgroundColor: color,
                              width: `${widthPct}%`,
                            }}
                          />
                        </div>
                        <span className="text-xs font-semibold text-foreground w-8 text-right">
                          {(score / 10).toFixed(1)}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      </section>
    </div>
  );
}

// packages/mobile/src/pages/compare/compare.vue
<template>
  <view class="page">
    <!-- 选择模式 -->
    <template v-if="mode === 'select'">
      <view class="topbar">
        <view class="back-btn" @tap="goHome">
          <text class="back-icon">&#xe612;</text>
        </view>
        <text class="topbar-title">公司对比</text>
        <view class="topbar-right" />
      </view>

      <view class="content">
        <view class="intro">
          <text class="intro-title">1v1 对比</text>
          <text class="intro-desc">从下方选择 2 家公司，查看六维横向对比与真实时薪</text>
        </view>

        <!-- 已选公司 chips -->
        <view v-if="selectedCompanies.length > 0" class="chips">
          <view
            v-for="c in selectedCompanies"
            :key="c.id"
            class="chip"
          >
            <text class="chip-text">{{ c.short_name || c.name }}</text>
            <text class="chip-close" @tap="removeSelected(c.id)">&#xe613;</text>
          </view>
          <text v-if="selectedIds.length < MAX_COMPARE" class="chip-hint">
            再选 {{ MAX_COMPARE - selectedIds.length }} 家
          </text>
        </view>

        <!-- 公司列表 -->
        <view v-if="loading" class="skeleton-list">
          <view v-for="i in 5" :key="i" class="skeleton-item" />
        </view>

        <view v-else class="company-list">
          <view
            v-for="c in results"
            :key="c.id"
            class="select-card"
            :class="{ 'select-card-active': selectedIds.includes(c.id) }"
            @tap="toggleSelect(c.id)"
          >
            <view class="select-card-info">
              <text class="select-card-name">{{ c.name }}</text>
              <text class="select-card-meta">
                {{ c.industry || '未知行业' }} · {{ c.scale || '未知规模' }}
              </text>
            </view>
            <view
              class="select-btn"
              :class="{ 'select-btn-active': selectedIds.includes(c.id) }"
            >
              <text class="select-btn-icon">{{ selectedIds.includes(c.id) ? '✓' : '+' }}</text>
            </view>
          </view>
        </view>
      </view>

      <!-- 底部操作栏 -->
      <view class="action-bar safe-area-bottom">
        <text class="action-count">
          已选 <text class="action-count-num">{{ selectedIds.length }}</text> / {{ MAX_COMPARE }}
        </text>
        <view
          class="action-btn"
          :class="{ 'action-btn-disabled': selectedIds.length !== 2 }"
          @tap="startCompare"
        >
          <text class="action-btn-text">开始 1v1 对比</text>
        </view>
      </view>
    </template>

    <!-- 对比模式 -->
    <template v-else>
      <view class="topbar">
        <view class="back-btn" @tap="backToSelect">
          <text class="back-icon">&#xe612;</text>
        </view>
        <text class="topbar-title">1v1 对比</text>
        <view class="topbar-right" />
      </view>

      <view v-if="compareLoading" class="skeleton-area">
        <view class="skeleton-block" style="height: 200rpx" />
        <view class="skeleton-block" style="height: 500rpx" />
      </view>

      <view v-else-if="compareData && compareData.companies.length === 2" class="compare-content">
        <!-- VS 头卡 -->
        <view class="vs-section">
          <view
            v-for="c in compareData.companies"
            :key="c.company_id"
            class="vs-card"
          >
            <text class="vs-card-name">{{ c.short_name || c.name }}</text>
            <view class="vs-card-score">
              <text class="vs-score-num">{{ (c.overall_score / 10).toFixed(1) }}</text>
            </view>
          </view>
          <view class="vs-badge">
            <text class="vs-badge-text">VS</text>
          </view>
        </view>

        <!-- 六维对比 -->
        <view class="card">
          <text class="card-title">六维度逐项对比</text>
          <view
            v-for="dimKey in DIMENSION_ORDER"
            :key="dimKey"
            class="compare-row"
          >
            <view class="compare-dim-label">
              <text class="compare-dim-text">{{ getDimLabel(dimKey) }}</text>
            </view>
            <view class="compare-scores">
              <view
                v-for="c in compareData.companies"
                :key="c.company_id"
                class="compare-score-item"
              >
                <text class="compare-score-name">{{ c.short_name || c.name }}</text>
                <view class="compare-score-bar-row">
                  <view class="compare-score-bar">
                    <view
                      class="compare-score-fill"
                      :style="{
                        width: `${getDimScore(c, dimKey)}%`,
                        backgroundColor: getDimColor(c, dimKey),
                      }"
                    />
                  </view>
                  <text class="compare-score-num">{{ (getDimScore(c, dimKey) / 10).toFixed(1) }}</text>
                </view>
              </view>
            </view>
          </view>
        </view>

        <!-- 真实时薪对比 -->
        <view v-if="hasWageData" class="card">
          <text class="card-title">真实时薪对比</text>
          <view class="wage-compare">
            <view
              v-for="c in compareData.companies"
              :key="c.company_id"
              class="wage-compare-item"
            >
              <text class="wage-compare-name">{{ c.short_name || c.name }}</text>
              <template v-if="analysisMap[c.company_id]?.real_hourly_wage">
                <view class="wage-compare-main">
                  <text class="wage-compare-amount">¥{{ analysisMap[c.company_id]!.real_hourly_wage.hourly_wage.toFixed(0) }}</text>
                  <text class="wage-compare-unit">/小时</text>
                </view>
                <view class="wage-compare-bar">
                  <view
                    class="wage-compare-fill"
                    :style="{
                      width: `${getWageHeight(c.company_id)}%`,
                      backgroundColor: getWageColor(c.company_id),
                    }"
                  />
                </view>
                <text class="wage-compare-meta">
                  月到手 ¥{{ (analysisMap[c.company_id]!.real_hourly_wage.monthly_take_home / 1000).toFixed(1) }}k
                </text>
              </template>
              <text v-else class="wage-no-data">暂无时薪数据</text>
            </view>
          </view>
        </view>
      </view>

      <view v-else class="empty-state">
        <text class="empty-text">对比数据加载失败，请重试</text>
      </view>
    </template>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { onShow } from "@dcloudio/uni-app";
import {
  searchCompanies,
  getCompanySummary,
  compareCompanies,
  getCompanyAnalysis,
} from "@/utils/api";
import type {
  CompanyListItem,
  CompanySummaryResponse,
  CompareResponse,
  CompanyAnalysisResponse,
  DimensionKey,
} from "@/utils/types";
import {
  DIMENSION_ORDER,
  DIMENSION_LABELS,
  LEVEL_COLORS,
} from "@/utils/constants";
import { getCompareIds, setCompareIds } from "@/utils/storage";

const MAX_COMPARE = 2;
const mode = ref<"select" | "compare">("select");
const selectedIds = ref<number[]>([]);
const results = ref<CompanyListItem[]>([]);
const summaryMap = ref<Record<number, CompanySummaryResponse>>({});
const loading = ref(true);

const compareData = ref<CompareResponse | null>(null);
const analysisMap = ref<Record<number, CompanyAnalysisResponse>>({});
const compareLoading = ref(false);

const selectedCompanies = computed(() =>
  selectedIds.value
    .map((id) => results.value.find((c) => c.id === id))
    .filter((c): c is CompanyListItem => !!c)
);

const hasWageData = computed(() => {
  if (!compareData.value) return false;
  return compareData.value.companies.some(
    (c) => analysisMap.value[c.company_id]?.real_hourly_wage?.hourly_wage > 0
  );
});

async function loadCompanies() {
  loading.value = true;
  try {
    const list = await searchCompanies("", 50, 0);
    results.value = list;
    const summaries = await Promise.all(
      list.map((c) => getCompanySummary(c.id))
    );
    const next: Record<number, CompanySummaryResponse> = {};
    for (const s of summaries) {
      if (s) next[s.company_id] = s;
    }
    summaryMap.value = next;
  } finally {
    loading.value = false;
  }
}

onMounted(() => {
  selectedIds.value = getCompareIds();
  loadCompanies();
});

onShow(() => {
  selectedIds.value = getCompareIds();
});

function toggleSelect(id: number) {
  const idx = selectedIds.value.indexOf(id);
  if (idx >= 0) {
    selectedIds.value = selectedIds.value.filter((x) => x !== id);
  } else if (selectedIds.value.length >= MAX_COMPARE) {
    selectedIds.value = [...selectedIds.value.slice(1), id];
  } else {
    selectedIds.value = [...selectedIds.value, id];
  }
  setCompareIds(selectedIds.value);
}

function removeSelected(id: number) {
  selectedIds.value = selectedIds.value.filter((x) => x !== id);
  setCompareIds(selectedIds.value);
}

async function startCompare() {
  if (selectedIds.value.length !== 2) return;
  mode.value = "compare";
  compareLoading.value = true;
  try {
    const res = await compareCompanies(selectedIds.value);
    if (res) {
      compareData.value = res;
      const analyses = await Promise.all(
        res.companies.map((c) => getCompanyAnalysis(c.company_id))
      );
      const next: Record<number, CompanyAnalysisResponse> = {};
      for (let i = 0; i < res.companies.length; i++) {
        if (analyses[i]) {
          next[res.companies[i].company_id] = analyses[i]!;
        }
      }
      analysisMap.value = next;
    }
  } finally {
    compareLoading.value = false;
  }
}

function backToSelect() {
  mode.value = "select";
  compareData.value = null;
  analysisMap.value = {};
}

function goHome() {
  uni.switchTab({ url: "/pages/index/index" });
}

function getDimLabel(key: string): string {
  return DIMENSION_LABELS[key as DimensionKey] || key;
}

function getDimScore(company: any, dimKey: string): number {
  const dim = company.dimensions.find((d: any) => d.key === dimKey);
  return dim ? dim.score : 0;
}

function getDimColor(company: any, dimKey: string): string {
  const dim = company.dimensions.find((d: any) => d.key === dimKey);
  if (!dim) return "#bdbdc2";
  return LEVEL_COLORS[dim.level as keyof typeof LEVEL_COLORS]?.hex || "#bdbdc2";
}

function getWageHeight(companyId: number): number {
  const wages = Object.values(analysisMap.value)
    .map((a) => a?.real_hourly_wage?.hourly_wage || 0)
    .filter((w) => w > 0);
  const maxWage = Math.max(...wages, 1);
  const wage = analysisMap.value[companyId]?.real_hourly_wage?.hourly_wage || 0;
  return maxWage > 0 ? (wage / maxWage) * 100 : 0;
}

function getWageColor(companyId: number): string {
  const wage = analysisMap.value[companyId]?.real_hourly_wage?.hourly_wage || 0;
  const p50 = analysisMap.value[companyId]?.real_hourly_wage?.industry_p50_hourly || 0;
  return p50 > 0 && wage >= p50 ? "#22c55e" : "#f59e0b";
}
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: #ffffff;
  padding-bottom: 200rpx;
}

.topbar {
  position: sticky;
  top: 0;
  z-index: 20;
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  border-bottom: 1rpx solid #efeff1;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 32rpx;
  height: 112rpx;
  padding-top: var(--status-bar-height);
}

.back-btn { padding: 8rpx 0; }
.back-icon { font-size: 40rpx; color: #18181b; }
.topbar-title { font-size: 32rpx; font-weight: 600; color: #18181b; }
.topbar-right { width: 60rpx; }

.content { padding: 32rpx; }

.intro { padding: 32rpx 0; }
.intro-title { display: block; font-size: 36rpx; font-weight: 600; color: #18181b; }
.intro-desc { display: block; font-size: 24rpx; color: #72727d; margin-top: 8rpx; }

.chips { display: flex; flex-wrap: wrap; align-items: center; gap: 16rpx; margin-bottom: 24rpx; }
.chip {
  display: flex; align-items: center; gap: 12rpx;
  padding: 12rpx 20rpx; border-radius: 999rpx;
  background: #18181b; color: #ffffff;
}
.chip-text { font-size: 24rpx; font-weight: 500; }
.chip-close { font-size: 28rpx; color: rgba(255,255,255,0.7); }
.chip-hint { font-size: 24rpx; color: #72727d; }

.company-list { display: flex; flex-direction: column; gap: 16rpx; }

.select-card {
  display: flex; align-items: center; gap: 24rpx;
  padding: 24rpx; border: 2rpx solid #efeff1; border-radius: 16rpx;
  background: #ffffff;
}
.select-card-active { border-color: #18181b; }
.select-card-info { flex: 1; min-width: 0; }
.select-card-name { display: block; font-size: 28rpx; font-weight: 600; color: #18181b; margin-bottom: 4rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.select-card-meta { display: block; font-size: 24rpx; color: #72727d; }
.select-btn {
  width: 80rpx; height: 80rpx; border-radius: 50%;
  display: flex; align-items: center; justify-content: center;
  background: #f7f7f8; flex-shrink: 0;
}
.select-btn-active { background: #18181b; }
.select-btn-icon { font-size: 36rpx; font-weight: 700; color: #72727d; }
.select-btn-active .select-btn-icon { color: #ffffff; }

.action-bar {
  position: fixed; bottom: 0; left: 0; right: 0; z-index: 40;
  display: flex; align-items: center; justify-content: space-between;
  padding: 24rpx 32rpx;
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  border-top: 1rpx solid #efeff1;
  padding-bottom: calc(24rpx + env(safe-area-inset-bottom));
}
.action-count { font-size: 24rpx; color: #72727d; }
.action-count-num { font-weight: 700; color: #18181b; }
.action-btn {
  padding: 0 48rpx; height: 80rpx; border-radius: 16rpx;
  background: #18181b; display: flex; align-items: center; justify-content: center;
}
.action-btn-disabled { opacity: 0.4; }
.action-btn-text { color: #ffffff; font-size: 28rpx; font-weight: 600; }

.skeleton-list { display: flex; flex-direction: column; gap: 16rpx; }
.skeleton-item { height: 128rpx; border-radius: 16rpx; background: #f7f7f8; animation: pulse 1.5s ease-in-out infinite; }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
.skeleton-area { padding: 32rpx; display: flex; flex-direction: column; gap: 24rpx; }
.skeleton-block { border-radius: 24rpx; background: #f7f7f8; animation: pulse 1.5s ease-in-out infinite; }

.compare-content { padding: 32rpx; }

.vs-section { position: relative; display: flex; gap: 16rpx; margin-bottom: 32rpx; }
.vs-card {
  flex: 1; padding: 24rpx; border: 1rpx solid #efeff1; border-radius: 16rpx;
  background: #ffffff; box-shadow: 0 4rpx 16rpx rgba(0,0,0,0.04);
}
.vs-card-name { display: block; font-size: 24rpx; font-weight: 700; color: #18181b; margin-bottom: 8rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.vs-score-num { font-size: 48rpx; font-weight: 800; color: #18181b; }
.vs-badge {
  position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);
  width: 64rpx; height: 64rpx; border-radius: 50%;
  background: #18181b; display: flex; align-items: center; justify-content: center;
  border: 4rpx solid #ffffff;
}
.vs-badge-text { font-size: 20rpx; font-weight: 800; color: #ffffff; }

.card {
  background: #ffffff; border: 1rpx solid #efeff1; border-radius: 24rpx;
  padding: 32rpx; margin-top: 32rpx; box-shadow: 0 4rpx 16rpx rgba(0,0,0,0.04);
}
.card-title { display: block; font-size: 32rpx; font-weight: 600; color: #18181b; margin-bottom: 24rpx; }

.compare-row { display: flex; align-items: center; gap: 24rpx; padding: 16rpx 0; border-top: 1rpx solid #efeff1; }
.compare-row:first-of-type { border-top: none; }
.compare-dim-label { width: 180rpx; flex-shrink: 0; }
.compare-dim-text { font-size: 24rpx; font-weight: 600; color: #18181b; }
.compare-scores { flex: 1; display: flex; flex-direction: column; gap: 12rpx; }
.compare-score-item { display: flex; flex-direction: column; gap: 4rpx; }
.compare-score-name { font-size: 20rpx; color: #72727d; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.compare-score-bar-row { display: flex; align-items: center; gap: 12rpx; }
.compare-score-bar { flex: 1; height: 12rpx; border-radius: 999rpx; background: #f7f7f8; overflow: hidden; }
.compare-score-fill { height: 100%; border-radius: 999rpx; }
.compare-score-num { font-size: 24rpx; font-weight: 700; color: #18181b; width: 56rpx; text-align: right; }

.wage-compare { display: flex; gap: 24rpx; }
.wage-compare-item { flex: 1; padding: 24rpx; border-radius: 16rpx; background: #f7f7f8; display: flex; flex-direction: column; gap: 12rpx; }
.wage-compare-name { font-size: 22rpx; font-weight: 600; color: #18181b; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.wage-compare-main { display: flex; align-items: baseline; gap: 8rpx; }
.wage-compare-amount { font-size: 48rpx; font-weight: 800; color: #18181b; }
.wage-compare-unit { font-size: 24rpx; color: #72727d; }
.wage-compare-bar { height: 16rpx; border-radius: 999rpx; background: #ffffff; overflow: hidden; }
.wage-compare-fill { height: 100%; border-radius: 999rpx; }
.wage-compare-meta { font-size: 20rpx; color: #72727d; }
.wage-no-data { font-size: 24rpx; color: #72727d; text-align: center; padding: 48rpx 0; }

.empty-state { padding: 160rpx 32rpx; text-align: center; }
.empty-text { font-size: 28rpx; color: #72727d; }
</style>
