// packages/mobile/src/pages/profile/profile.vue
<template>
  <view class="page" :style="{ '--status-bar-height': statusBarHeight + 'px', '--tabbar-height': tabbarHeight + 'px' }">
    <!-- 用户信息卡 -->
    <view class="user-section">
      <view class="user-card">
        <!-- 未登录 -->
        <view v-if="!isLoggedIn" class="not-logged-in">
          <view class="avatar-placeholder">
            <Icon name="user" :size="64" color="#9333ea" />
          </view>
          <view class="login-prompt">
            <text class="login-prompt-title">开启你的求职决策</text>
            <text class="login-prompt-desc">登录后同步收藏、对比与浏览记录</text>
          </view>
        </view>

        <!-- 已登录 -->
        <view v-else class="logged-in">
          <view class="avatar-box">
            <view class="avatar-inner">
              <text class="avatar-text">{{ username.charAt(0) || 'Z' }}</text>
            </view>
          </view>
          <view class="user-info">
            <view class="user-name-row">
              <text class="user-name">{{ username }}</text>
              <view class="vip-badge">
                <text class="vip-text">VIP</text>
              </view>
            </view>
            <text class="user-bio">{{ bio || '欢迎回来 · 用好六维决策更聪明' }}</text>
          </view>
        </view>

        <!-- 登录按钮 -->
        <view v-if="!isLoggedIn" class="login-actions">
          <view class="login-btn" @tap="goLogin">
            <text class="login-btn-text">登录 / 注册</text>
          </view>
          <view class="browse-btn" @tap="goHome">
            <text class="browse-btn-text">随便看看</text>
          </view>
        </view>
      </view>
    </view>

    <!-- 我的工具（登录态） -->
    <view v-if="isLoggedIn" class="tools-section">
      <text class="section-label">我的工具</text>
      <view class="tools-grid">
        <view class="tool-item" @tap="showComingSoon">
          <Icon name="star" :size="44" color="#15803d" />
          <text class="tool-value">{{ favCount }}</text>
          <text class="tool-label">收藏</text>
        </view>
        <view class="tool-item" @tap="goCompare">
          <Icon name="scale" :size="44" color="#0369a1" />
          <text class="tool-value">0</text>
          <text class="tool-label">对比</text>
        </view>
        <view class="tool-item" @tap="showComingSoon">
          <Icon name="clipboard" :size="44" color="#b45309" />
          <text class="tool-value">{{ historyCount }}</text>
          <text class="tool-label">浏览</text>
        </view>
        <view class="tool-item" @tap="showComingSoon">
          <Icon name="edit" :size="44" color="#9333ea" />
          <text class="tool-value">{{ reviewCount }}</text>
          <text class="tool-label">评价</text>
        </view>
      </view>
    </view>

    <!-- 菜单 -->
    <view class="menu-section">
      <text class="section-label">账号</text>
      <view class="menu-card">
        <view class="menu-item" @tap="showComingSoon">
          <view class="menu-icon-box" style="background: #e0f2fe">
            <Icon name="lock" :size="32" color="#0369a1" />
          </view>
          <text class="menu-label">账号安全</text>
          <text class="menu-value">未绑定</text>
          <text class="menu-arrow">></text>
        </view>
      </view>
    </view>

    <view class="menu-section">
      <text class="section-label">偏好与帮助</text>
      <view class="menu-card">
        <view class="menu-item" @tap="showComingSoon">
          <view class="menu-icon-box" style="background: #efeff1">
            <Icon name="moon" :size="32" color="#55555e" />
          </view>
          <text class="menu-label">深色模式</text>
          <text class="menu-value">跟随系统</text>
          <text class="menu-arrow">></text>
        </view>
        <view class="menu-item border-top" @tap="showComingSoon">
          <view class="menu-icon-box" style="background: #fef3c7">
            <Icon name="bell" :size="32" color="#b45309" />
          </view>
          <text class="menu-label">消息通知</text>
          <text class="menu-value">已开启</text>
          <text class="menu-arrow">></text>
        </view>
        <view class="menu-item border-top" @tap="showComingSoon">
          <view class="menu-icon-box" style="background: #dcfce7">
            <Icon name="info" :size="32" color="#15803d" />
          </view>
          <text class="menu-label">关于真职</text>
          <text class="menu-arrow">></text>
        </view>
        <view class="menu-item border-top" @tap="showComingSoon">
          <view class="menu-icon-box" style="background: #f3e8ff">
            <Icon name="chat" :size="32" color="#9333ea" />
          </view>
          <text class="menu-label">帮助与反馈</text>
          <text class="menu-arrow">></text>
        </view>
      </view>
    </view>

    <!-- 退出登录 -->
    <view v-if="isLoggedIn" class="menu-section">
      <view class="menu-card">
        <view class="menu-item" @tap="handleLogout">
          <view class="menu-icon-box" style="background: #fff1f2">
            <Icon name="logout" :size="32" color="#e11d48" />
          </view>
          <text class="menu-label" style="color: #e11d48">退出登录</text>
        </view>
      </view>
    </view>

    <!-- Toast -->
    <view v-if="toast" class="toast">
      <text class="toast-text">{{ toast }}</text>
    </view>
    <TabBar current="profile" />
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { onShow } from "@dcloudio/uni-app";
import { getFavorites, getMe } from "@/utils/api";
import {
  hasToken,
  removeToken,
  Storage,
} from "@/utils/storage";
import { getSystemLayout } from "@/utils/constants";

const { statusBarHeight, tabbarHeight } = getSystemLayout();
const isLoggedIn = ref(false);
const username = ref("");
const bio = ref("");
const favCount = ref(0);
const historyCount = ref(0);
const reviewCount = ref(0);
const toast = ref("");

function loadLocalCounts() {
  const favs = Storage.getJSON<any[]>("zjob_favorites", []);
  favCount.value = Array.isArray(favs) ? favs.length : 0;
  const history = Storage.getJSON<any[]>("zjob_view_history", []);
  historyCount.value = Array.isArray(history) ? history.length : 0;
  const reviews = Storage.getJSON<any[]>("zjob_reviews", []);
  reviewCount.value = Array.isArray(reviews) ? reviews.length : 0;
}

onMounted(() => {
  checkLogin();
});

onShow(() => {
  uni.hideTabBar();
  checkLogin();
  if (isLoggedIn.value) {
    loadFavorites();
  } else {
    loadLocalCounts();
  }
});

function checkLogin() {
  isLoggedIn.value = hasToken();
  if (!isLoggedIn.value) {
    loadLocalCounts();
    return;
  }
  const savedName = Storage.get("zjob_nickname") || "";
  if (savedName) username.value = savedName;
  getMe()
    .then((profile) => {
      username.value = profile.nickname || profile.username;
      if (profile.bio) bio.value = profile.bio;
    })
    .catch(() => {
      const role = Storage.get("zjob_role");
      username.value = Storage.get("zjob_nickname") || (role === "admin" ? "运营同学" : "真职用户");
    });
}

async function loadFavorites() {
  try {
    const items = await getFavorites();
    favCount.value = Array.isArray(items) ? items.length : 0;
  } catch {
    loadLocalCounts();
  }
}

function handleLogout() {
  removeToken();
  isLoggedIn.value = false;
  showToast("已退出登录");
}

function goLogin() {
  uni.navigateTo({ url: "/pages/login/login" });
}

function goHome() {
  uni.switchTab({ url: "/pages/index/index" });
}

function goCompare() {
  uni.switchTab({ url: "/pages/compare/compare" });
}

function showComingSoon() {
  showToast("功能即将上线，敬请期待");
}

function showToast(msg: string) {
  toast.value = msg;
  setTimeout(() => {
    toast.value = "";
  }, 2000);
}
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: #f7f7f8;
  padding-bottom: var(--tabbar-height);
}

.user-section { padding: calc(var(--status-bar-height) + 40rpx) 32rpx 16rpx; }

.user-card {
  background: #ffffff;
  border: 1rpx solid #e4e4e7;
  border-radius: 16px;
  padding: 40rpx;
  box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.06);
}

.not-logged-in { display: flex; align-items: center; gap: 32rpx; }
.avatar-placeholder {
  width: 128rpx; height: 128rpx; border-radius: 50%;
  background: #f3e8ff; display: flex; align-items: center; justify-content: center;
  flex-shrink: 0;
}
.avatar-icon { font-size: 64rpx; color: #9333ea; }
.login-prompt { flex: 1; }
.login-prompt-title { display: block; font-size: 32rpx; font-weight: 600; color: #18181b; }
.login-prompt-desc { display: block; font-size: 24rpx; color: #72727d; margin-top: 8rpx; line-height: 1.5; }

.logged-in { display: flex; align-items: center; gap: 32rpx; }
.avatar-box {
  width: 128rpx; height: 128rpx; border-radius: 50%;
  background: linear-gradient(135deg, #d8b4fe, #9333ea, #7e22ce);
  padding: 4rpx; flex-shrink: 0;
}
.avatar-inner {
  width: 100%; height: 100%; border-radius: 50%;
  background: #dcfce7; display: flex; align-items: center; justify-content: center;
  overflow: hidden;
}
.avatar-text { font-size: 48rpx; font-weight: 700; color: #15803d; }
.user-info { flex: 1; min-width: 0; }
.user-name-row { display: flex; align-items: center; gap: 16rpx; }
.user-name { font-size: 32rpx; font-weight: 600; color: #18181b; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.vip-badge {
  padding: 4rpx 16rpx; border-radius: 999rpx;
  background: linear-gradient(90deg, #a855f7, #7e22ce);
}
.vip-text { font-size: 18rpx; font-weight: 700; color: #ffffff; }
.user-bio { display: block; font-size: 24rpx; color: #72727d; margin-top: 8rpx; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.login-actions { display: flex; gap: 16rpx; margin-top: 32rpx; }
.login-btn {
  flex: 1; height: 80rpx; border-radius: 16rpx;
  background: #0284c7; display: flex; align-items: center; justify-content: center;
}
.login-btn-text { color: #ffffff; font-size: 28rpx; font-weight: 600; }
.browse-btn {
  height: 80rpx; padding: 0 32rpx; border-radius: 16rpx;
  border: 1rpx solid #e4e4e7; display: flex; align-items: center; justify-content: center;
}
.browse-btn-text { color: #18181b; font-size: 28rpx; font-weight: 500; }

.tools-section { padding: 16rpx 32rpx; }
.section-label { display: block; font-size: 24rpx; font-weight: 600; color: #72727d; padding: 0 8rpx 16rpx; }
.tools-grid {
  display: flex; justify-content: space-around;
  background: #ffffff; border: 1rpx solid #e4e4e7; border-radius: 16px;
  padding: 32rpx 16rpx; box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.06);
}
.tool-item { display: flex; flex-direction: column; align-items: center; gap: 8rpx; flex: 1; }
.tool-icon { font-size: 40rpx; }
.tool-value { font-size: 32rpx; font-weight: 700; color: #18181b; }
.tool-label { font-size: 20rpx; color: #72727d; }

.menu-section { padding: 16rpx 32rpx; }
.menu-card {
  background: #ffffff; border: 1rpx solid #e4e4e7; border-radius: 16px;
  overflow: hidden; box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.06);
}
.menu-item {
  display: flex; align-items: center; gap: 24rpx;
  padding: 28rpx 32rpx;
}
.border-top { border-top: 1rpx solid #efeff1; }
.menu-icon-box {
  width: 72rpx; height: 72rpx; border-radius: 16rpx;
  display: flex; align-items: center; justify-content: center; flex-shrink: 0;
}
.menu-icon { font-size: 32rpx; }
.menu-label { flex: 1; font-size: 28rpx; font-weight: 500; color: #18181b; }
.menu-value { font-size: 24rpx; color: #72727d; }
.menu-arrow { font-size: 28rpx; color: #9898a0; }

.toast {
  position: fixed; bottom: calc(var(--tabbar-height) + 40rpx); left: 50%; transform: translateX(-50%);
  padding: 16rpx 32rpx; border-radius: 16rpx;
  background: #2a2a2f; z-index: 999;
}
.toast-text { color: #ffffff; font-size: 28rpx; }
</style>

// web/app/m/profile/page.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import {
  Bell,
  ChevronRight,
  CircleHelp,
  Clock,
  Crown,
  Heart,
  Info,
  LogOut,
  Moon,
  ScrollText,
  Shield,
  Sparkles,
  Star,
  User as UserIcon,
  Edit3,
} from "lucide-react";
import { getFavorites, getMe } from "@/lib/api";

// 移动端个人中心页面
export default function MobileProfilePage() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState("");
  const [bio, setBio] = useState("");
  const [avatar, setAvatar] = useState("");
  const [toast, setToast] = useState("");
  const [favCount, setFavCount] = useState(0);
  const [historyCount, setHistoryCount] = useState(0);
  const [reviewCount, setReviewCount] = useState(0);

  // 读取本地存储的统计数量
  const loadLocalCounts = () => {
    try {
      const favs = JSON.parse(localStorage.getItem("zjob_favorites") || "[]");
      setFavCount(Array.isArray(favs) ? favs.length : 0);
    } catch {
      setFavCount(0);
    }
    try {
      const history = JSON.parse(localStorage.getItem("zjob_view_history") || "[]");
      setHistoryCount(Array.isArray(history) ? history.length : 0);
    } catch {
      setHistoryCount(0);
    }
    try {
      const reviews = JSON.parse(localStorage.getItem("zjob_reviews") || "[]");
      setReviewCount(Array.isArray(reviews) ? reviews.length : 0);
    } catch {
      setReviewCount(0);
    }
  };

  useEffect(() => {
    const token = localStorage.getItem("zjob_token");
    setIsLoggedIn(!!token);
    if (!token) {
      loadLocalCounts();
      return;
    }
    const savedAvatar = localStorage.getItem("zjob_avatar");
    if (savedAvatar) setAvatar(savedAvatar);
    getMe()
      .then((profile) => {
        setUsername(profile.nickname || profile.username);
        if (profile.bio) setBio(profile.bio);
      })
      .catch(() => {
        const role = localStorage.getItem("zjob_role");
        const defaultName = role === "admin" ? "运营同学" : "真职用户";
        setUsername(localStorage.getItem("zjob_nickname") || defaultName);
        const savedBio = localStorage.getItem("zjob_bio");
        if (savedBio) setBio(savedBio);
      });
    // 收藏数：优先从后端获取
    getFavorites()
      .then((items) => setFavCount(Array.isArray(items) ? items.length : 0))
      .catch(() => {
        try {
          const favs = JSON.parse(localStorage.getItem("zjob_favorites") || "[]");
          setFavCount(Array.isArray(favs) ? favs.length : 0);
        } catch {
          setFavCount(0);
        }
      });
    // 浏览/评价数：从 localStorage 读取
    try {
      const history = JSON.parse(localStorage.getItem("zjob_view_history") || "[]");
      setHistoryCount(Array.isArray(history) ? history.length : 0);
    } catch {
      setHistoryCount(0);
    }
    try {
      const reviews = JSON.parse(localStorage.getItem("zjob_reviews") || "[]");
      setReviewCount(Array.isArray(reviews) ? reviews.length : 0);
    } catch {
      setReviewCount(0);
    }
  }, []);

  // 页面重新可见时刷新统计（从收藏列表等返回）
  useEffect(() => {
    const handler = () => loadLocalCounts();
    window.addEventListener("focus", handler);
    return () => window.removeEventListener("focus", handler);
  }, []);

  const handleLogout = () => {
    localStorage.removeItem("zjob_token");
    localStorage.removeItem("zjob_role");
    setIsLoggedIn(false);
  };

  const showComingSoon = () => {
    setToast("功能即将上线，敬请期待");
    setTimeout(() => setToast(""), 2000);
  };

  // 快捷统计
  const stats = [
    {
      icon: Heart,
      label: "收藏",
      value: favCount,
      text: "text-emote-mint-700",
      badge: "bg-emote-mint-600 text-white",
      href: "/m/profile/favorites",
    },
    {
      icon: ScrollText,
      label: "对比",
      value: 0,
      text: "text-emote-sky-700",
      badge: "bg-emote-sky-600 text-white",
      href: "/m/compare",
    },
    {
      icon: Clock,
      label: "浏览",
      value: historyCount,
      text: "text-emote-cream-700",
      badge: "bg-emote-cream-600 text-white",
      href: "/m/profile/history",
    },
    {
      icon: Star,
      label: "评价",
      value: reviewCount,
      text: "text-emote-lavender-700",
      badge: "bg-emote-lavender-600 text-white",
      href: "/m/profile/reviews",
    },
  ];

  // 菜单组配置
  const menuGroups: {
    title: string;
    items: {
      icon: typeof UserIcon;
      label: string;
      value?: string;
      href?: string;
      onClick?: () => void;
      danger?: boolean;
      accentBg?: string;
      accentText?: string;
    }[];
  }[] = [
    {
      title: "账号",
      items: [
        {
          icon: Shield,
          label: "账号安全",
          value: "未绑定",
          onClick: showComingSoon,
          accentBg: "bg-emote-sky-100",
          accentText: "text-emote-sky-700",
        },
      ],
    },
    {
      title: "偏好与帮助",
      items: [
        {
          icon: Moon,
          label: "深色模式",
          value: "跟随系统",
          accentBg: "bg-emote-charcoal-100",
          accentText: "text-emote-charcoal-600",
        },
        {
          icon: Bell,
          label: "消息通知",
          value: "已开启",
          accentBg: "bg-emote-cream-100",
          accentText: "text-emote-cream-700",
        },
        {
          icon: Info,
          label: "关于真职",
          onClick: showComingSoon,
          accentBg: "bg-emote-mint-100",
          accentText: "text-emote-mint-700",
        },
        {
          icon: CircleHelp,
          label: "帮助与反馈",
          onClick: showComingSoon,
          accentBg: "bg-emote-lavender-100",
          accentText: "text-emote-lavender-700",
        },
      ],
    },
  ];

  return (
    <div className="bg-background min-h-screen pb-6">
      <div className="max-w-[430px] mx-auto">
        {/* 用户信息卡（含统计区） */}
        <section className="px-4 pt-5 pb-4">
          <div className="bg-card border border-border rounded-xl p-5 shadow-card">
            {/* 未登录态：引导登录 */}
            {!isLoggedIn ? (
              <div className="flex items-center gap-4">
                <div className="w-16 h-16 rounded-full bg-emote-lavender-100 flex items-center justify-center shrink-0">
                  <UserIcon className="w-8 h-8 text-emote-lavender-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <h2 className="text-lg font-semibold text-foreground">
                    开启你的求职决策
                  </h2>
                  <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
                    登录后同步收藏、对比与浏览记录
                  </p>
                </div>
              </div>
            ) : (
              <>
                <div className="flex items-center gap-4">
                  <div className="relative shrink-0">
                    <div className="w-16 h-16 rounded-full bg-gradient-to-br from-emote-lavender-300 via-emote-lavender-500 to-emote-lavender-700 p-[2px]">
                      <div className="w-full h-full rounded-full bg-emote-mint-100 overflow-hidden flex items-center justify-center">
                        {avatar ? (
                          <img src={avatar} alt="头像" className="w-full h-full object-cover" />
                        ) : (
                          <UserIcon className="w-8 h-8 text-emote-mint-700" />
                        )}
                      </div>
                    </div>
                    <Link
                      href="/m/profile/edit"
                      className="absolute -bottom-0.5 -right-0.5 w-6 h-6 rounded-full bg-card border border-border flex items-center justify-center shadow-card"
                      aria-label="编辑头像"
                    >
                      <Edit3 className="w-3 h-3 text-muted-foreground" />
                    </Link>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h2 className="text-lg font-semibold text-foreground truncate">
                        {username}
                      </h2>
                      <span className="inline-flex items-center gap-0.5 shrink-0 bg-gradient-to-r from-emote-lavender-500 to-emote-lavender-700 text-white text-[10px] font-bold px-2 py-0.5 rounded-full shadow-sm">
                        <Crown className="w-3 h-3" />
                        VIP 会员
                      </span>
                    </div>
                    <p className="text-xs text-muted-foreground mt-1 truncate">
                      {bio || "欢迎回来 · 用好六维决策更聪明"}
                    </p>
                  </div>
                  <Link
                    href="/m/profile/edit"
                    className="shrink-0 p-2 rounded-lg bg-secondary text-muted-foreground hover:text-foreground"
                    aria-label="编辑资料"
                  >
                    <Edit3 className="w-4 h-4" />
                  </Link>
                </div>

                {/* VIP 会员信息条 */}
                <button
                  onClick={showComingSoon}
                  className="mt-4 w-full rounded-lg bg-gradient-to-r from-emote-lavender-50 via-emote-lavender-100 to-emote-lavender-50 border border-emote-lavender-200/60 p-3 flex items-center gap-3 active:opacity-80 transition-opacity"
                >
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-emote-lavender-400 to-emote-lavender-600 flex items-center justify-center shrink-0 shadow-sm">
                    <Sparkles className="w-5 h-5 text-white" />
                  </div>
                  <div className="flex-1 min-w-0 text-left">
                    <div className="flex items-center gap-1.5">
                      <span className="text-sm font-semibold text-emote-lavender-900">
                        VIP 会员
                      </span>
                      <span className="text-[10px] px-1.5 py-0.5 rounded bg-emote-lavender-500/20 text-emote-lavender-700 font-medium">
                        畅享特权
                      </span>
                    </div>
                    <p className="text-[11px] text-emote-lavender-700/80 mt-0.5 truncate">
                      有效期至 2026-12-31 · 六维评估无限制
                    </p>
                  </div>
                  <ChevronRight className="w-4 h-4 text-emote-lavender-600/70 shrink-0" />
                </button>
              </>
            )}

            {/* 登录按钮（未登录态） */}
            {!isLoggedIn && (
              <div className="mt-4 flex items-center gap-2">
                <Link
                  href="/m/login"
                  className="flex-1 inline-flex items-center justify-center h-10 rounded-lg bg-emote-sky-600 text-white text-sm font-semibold hover:bg-emote-sky-700 transition-colors"
                >
                  登录 / 注册
                </Link>
                <Link
                  href="/m"
                  className="inline-flex items-center justify-center h-10 px-4 rounded-lg border border-border bg-background text-sm font-medium text-foreground hover:bg-secondary/50 transition-colors shrink-0"
                >
                  随便看看
                </Link>
              </div>
            )}
          </div>
        </section>

        {/* 我的工具（登录态展示） */}
        {isLoggedIn && (
          <section className="px-4 mt-1">
            <h3 className="text-xs font-semibold text-muted-foreground px-1 mb-2 tracking-wide">
              我的工具
            </h3>
            <div className="bg-card border border-border rounded-xl shadow-card px-2 py-3 flex items-center justify-around">
              {stats.map((s) => {
                const Icon = s.icon;
                return (
                  <Link
                    key={s.label}
                    href={s.href}
                    className="flex flex-col items-center gap-1 active:opacity-60 transition-opacity flex-1"
                  >
                    <div className="relative">
                      <Icon className={`w-5 h-5 ${s.text}`} />
                      <span
                        className={`absolute -top-1 -right-2 min-w-[14px] h-3.5 px-1 rounded-full ${s.badge} text-[9px] font-bold flex items-center justify-center ring-2 ring-card`}
                      >
                        {s.value}
                      </span>
                    </div>
                    <span className="text-[10px] text-muted-foreground">
                      {s.label}
                    </span>
                  </Link>
                );
              })}
            </div>
          </section>
        )}

        {/* 菜单组 */}
        <div className="px-4 space-y-5 mt-4">
          {menuGroups.map((group) => (
            <section key={group.title}>
              <h3 className="text-xs font-semibold text-muted-foreground px-1 mb-2 tracking-wide">
                {group.title}
              </h3>
              <div className="bg-card border border-border rounded-xl overflow-hidden shadow-card">
                {group.items.map((item, idx) => {
                  const Icon = item.icon;
                  const content = (
                    <div
                      className={`flex items-center gap-3 px-4 py-3.5 hover:bg-secondary/50 transition-colors ${
                        idx > 0 ? "border-t border-border" : ""
                      }`}
                    >
                      <div
                        className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 ${
                          item.danger
                            ? "bg-emote-rose-50 text-emote-rose-600"
                            : `${item.accentBg ?? "bg-secondary"} ${
                                item.accentText ?? "text-foreground"
                              }`
                        }`}
                      >
                        <Icon className="w-4 h-4" />
                      </div>
                      <span className="flex-1 text-sm font-medium text-foreground">
                        {item.label}
                      </span>
                      {item.value && (
                        <span className="text-xs text-muted-foreground mr-0.5">
                          {item.value}
                        </span>
                      )}
                      {item.href && !item.onClick && (
                        <ChevronRight className="w-4 h-4 text-muted-foreground shrink-0" />
                      )}
                    </div>
                  );
                  return item.href ? (
                    <Link key={item.label} href={item.href}>
                      {content}
                    </Link>
                  ) : (
                    <button
                      key={item.label}
                      onClick={item.onClick}
                      className="w-full text-left"
                    >
                      {content}
                    </button>
                  );
                })}
              </div>
            </section>
          ))}

          {/* 退出登录（仅登录态显示） */}
          {isLoggedIn && (
            <section>
              <div className="bg-card border border-border rounded-xl overflow-hidden shadow-card">
                <button
                  onClick={handleLogout}
                  className="w-full flex items-center gap-3 px-4 py-3.5 hover:bg-secondary/50 transition-colors text-left"
                >
                  <div className="w-9 h-9 rounded-lg bg-emote-rose-50 text-emote-rose-600 flex items-center justify-center shrink-0">
                    <LogOut className="w-4 h-4" />
                  </div>
                  <span className="flex-1 text-sm font-semibold text-emote-rose-600">
                    退出登录
                  </span>
                </button>
              </div>
            </section>
          )}
        </div>
      </div>

      {/* Toast 提示 */}
      {toast && (
        <div className="fixed bottom-24 left-1/2 -translate-x-1/2 z-50 px-4 py-2 rounded-lg bg-emote-charcoal-800 text-white text-sm shadow-modal">
          {toast}
        </div>
      )}
    </div>
  );
}
